name: 'tscircuit Deploy'
description: 'Deploy tscircuit projects with automatic preview builds and semantic versioning'
author: 'tscircuit'
branding:
  icon: 'zap'
  color: 'blue'

inputs:
  args:
    description: 'Arguments to pass to tscircuit CLI'
    required: false
    default: 'deploy'
  
  github-token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}
  
  deploy-url:
    description: 'Base URL for deployment service'
    required: false
    default: 'https://deploy.tscircuit.com'
  
  timeout:
    description: 'Build timeout in minutes'
    required: false
    default: '10'
  
  working-directory:
    description: 'Working directory for tscircuit commands'
    required: false
    default: '.'

outputs:
  deployment-id:
    description: 'Unique identifier for this deployment'
  
  preview-url:
    description: 'URL for preview deployment (if applicable)'
  
  package-version:
    description: 'Published package version (for production deployments)'
  
  build-time:
    description: 'Total build time in seconds'
  
  circuit-count:
    description: 'Number of circuit files processed'

runs:
  using: 'node20'
  main: 'dist/index.js' 