name: "tscircuit Deploy"
description: "Deploy tscircuit projects with automatic preview builds and semantic versioning"
author: "tscircuit"
branding:
  icon: "zap"
  color: "blue"

inputs:
  github-token:
    description: "GitHub token for API access"
    required: false
    default: ${{ github.token }}

  working-directory:
    description: "Working directory for tscircuit commands"
    required: false
    default: "."

  deploy-server-url:
    description: "URL of the tscircuit deploy server"
    required: false
    default: "https://deploy.tscircuit.com"

  create-release:
    description: "Create a release for the project"
    required: false
    default: "false"

outputs:
  deployment-id:
    description: "Unique identifier for this deployment"

  preview-url:
    description: "URL for preview deployment (if applicable)"

  package-version:
    description: "Published package version (for production deployments)"

  build-time:
    description: "Total build time in seconds"

  circuit-count:
    description: "Number of circuit files processed"

runs:
  using: "node20"
  main: "dist/index.js"
