name: Simple tscircuit Deploy

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      deployments: write
      statuses: write
      checks: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Build tscircuit
        working-directory: ./packages/github-action
        run: |
          bun install
          bun x tsup ./src/index.ts --format esm

      - name: Deploy tscircuit
        uses: ./packages/github-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: "."
          deploy-server-url: https://deploy-tsc-test.vercel.app
          create-release: false
